# Generated by Django 5.1.2 on 2024-11-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='Product_Description',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
